### ISSUE TITLE
レス（リプライ機能）

### ISSUE THREAD

**Issue by ShinoharaTa** [ShinoharaTa/nchan#11]
メモ
```
tags: [
  [
    "e",
    "hex_id",
    "",
    "reply",
  ]
]
```

**Comment by ShinoharaTa** [comment]
@an-apco 
リプライ先に設定するためのボタンを投稿のところに表示しようと思うんだ。
使うのはsvgでなんかそれっぽいのがないかこちらで探す！

どこにいれればいいとおもう？

![image](https://github.com/user-attachments/assets/83845ddd-15a3-4c89-970f-f29fa1e8bf3c)

**Comment by an-apco** [comment]
@ShinoharaTa これってリプライボタン押したらテキストエリアに`>>リプライ先`みたいに仕組みかな？
それだったら、テキストの一番下左でいいとおもう。

5ちゃんと同じような位置

**Comment by ShinoharaTa** [comment]
あざます！
多分こんな感じにする！

----------

💬リプに設定

**Comment by an-apco** [comment]
かわいい
いいと思います。
ありがとう
