### ISSUE TITLE
#2 のハッシュから色を付ける場合の背景色視認性向上

### ISSUE THREAD

**Issue by ShinoharaTa** [ShinoharaTa/nchan#15]
#2 対応中に見つかった問題
現状単色のため文字色・背景色になじまない場合があり案を検討中

- HSLで表記する（16進数のカラーコードを維持したまま彩度、明度を変更するため変換式の仕様決めが必要
- 背景色を白、#xxxxxx88 をその上に重ね、文字色を設定する

**Comment by ShinoharaTa** [comment]
#xxxxxx88 を使用すると文字色にあれこれしなくてもいい感じのバランスになることの証明
![image](https://github.com/user-attachments/assets/153bf40d-8832-4676-80af-d729fe9a221d)

**Comment by ShinoharaTa** [comment]
@an-apco 
上の画像の通りで、 b3e43e ってかなり明るめなんだけど #xxxxxx88 になるとそれなりに視認性が確保されるのでこの方式を使用する予定
もうちょっとアルファ値を調整して色を薄めようかなおもう。

**Comment by an-apco** [comment]
@ShinoharaTa アルファ値の調整はrgba指定になるから、結局16進数で対応できない気がする

**Comment by an-apco** [comment]
嘘ついた、 #xxxxxx88でいけました

**Comment by an-apco** [comment]
透過率 | 下2桁
-- | --
0%（透過しない） | FF
5% | F2
10% | E6
15% | D9
20% | CC
25% | BF
30% | B3
35% | A6
40% | 99
45% | 8C
50% | 80
55% | 73
60% | 66
65% | 59
70% | 4D
75% | 40
80% | 33
85% | 26
90% | 1A
95% | 0D
100%（見えない） | 00

**Comment by ShinoharaTa** [comment]
#xxxxxx40 ぐらいでもうちょっと薄めに色を付けてみる！
スレッドの背景色も #xxxxxx40 にして、文字色はそのままにしようかなと少し思っていたりするけど

**Comment by ShinoharaTa** [comment]
視認性の比較
![image](https://github.com/user-attachments/assets/302b77c1-6f1b-46c9-bdea-3ee5675a6aec)
![image](https://github.com/user-attachments/assets/25ff8464-8a84-4dba-9e82-e04238fd890b)

**Comment by ShinoharaTa** [comment]
うすすぎｗ

**Comment by ShinoharaTa** [comment]
#xxxxxx80 にしてみたかんじ。見やすさ
![image](https://github.com/user-attachments/assets/f9a19997-165d-48c2-a418-af5ec8b88e4a)

**Comment by an-apco** [comment]
80か66あたりかなあとおもってた
66は結構ライドダークどっちにも適用できるイメージ

**Comment by ShinoharaTa** [comment]
66だと背景と文字色のコントラスト差もいい感じなのでこれでいきます。

**Comment by an-apco** [comment]
はい、よろしくお願いします。
調整ありがとうございます！

**Comment by ShinoharaTa** [comment]
このへんの名前の色がコントラスト差ほぼ出ないのどうにかしたいところ
![image](https://github.com/user-attachments/assets/908bd40b-63de-48b3-bd06-e451da0b855c)

**Comment by an-apco** [comment]
んちゃんねるから〜の部分、カラフルで見づらいという意見があるので、そこは文字色統一して、別の部分で色を入れたいと思っていたところです。
別でIssue作って、私の方で直しても良いですか？

**Comment by ShinoharaTa** [comment]
助かる！

**Comment by ShinoharaTa** [comment]
スレッドのユーザー名対応は、あんずにお任せ！
#22
